---
# handlers file for configure-solr-for-hydra-role


- name: restart solr
  shell: systemctl stop solr && sleep 10
  become: yes
  notify: start solr

- name: start solr
  shell: systemctl start solr
  become: yes

  
